# Generated by Django 5.1.1 on 2025-02-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalbalance',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
