# Generated by Django 5.1.1 on 2024-12-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_express_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='express',
            old_name='income_category',
            new_name='express_category',
        ),
    ]
