# Generated by Django 5.1.1 on 2025-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.BooleanField(default=False),
        ),
    ]
