# Generated by Django 5.1.1 on 2025-04-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_project_project_duration_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
