# Generated by Django 5.1.6 on 2025-02-25 18:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_futurework_note_project_projectplan_shedulemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
