# Generated by Django 5.1.6 on 2025-02-25 18:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_tasks_task_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurework',
            name='work_details',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_details',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='topic_list',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
