# Generated by Django 5.1.6 on 2025-02-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_futurework_work_details_alter_note_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedulemail',
            name='sent_to',
            field=models.EmailField(max_length=254),
        ),
    ]
