# Generated by Django 5.1.6 on 2025-02-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_alter_shedulemail_sent_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shedulemail',
            old_name='email',
            new_name='message',
        ),
        migrations.AddField(
            model_name='shedulemail',
            name='sent_from',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
