# Generated by Django 5.1.6 on 2025-02-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_rename_email_shedulemail_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedulemail',
            name='shedule_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
